### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by bderusha** [pghs/QuizTube#1]
Wondering how best to utilize these

**Comment by urtonj** [comment]
Is this going to be an issue?

**Comment by bderusha** [comment]
haha, sorry I forgot you were a watcher on this.  I'm thinking about making a proposal about how we can better utilize issues @ work and wanted to test some things out first.

**Comment by urtonj** [comment]
Nice. Do you use Github for pull requests?

**Comment by bderusha** [comment]
We do! But we use JIRA for issue tracking

**Comment by urtonj** [comment]
We use Unfuddle, its :-1:
